AllCops:
  TargetRubyVersion: 2.4.1

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 17

Layout/LineLength:
  Max: 120
